admin_codes:
    path:     /
    defaults: { _controller: "EdpMainBundle:code:index" }

admin_codes_show:
    path:     /{id}/show
    defaults: { _controller: "EdpMainBundle:code:show" }

admin_codes_new:
    path:     /new
    defaults: { _controller: "EdpMainBundle:code:new" }

admin_codes_create:
    path:     /create
    defaults: { _controller: "EdpMainBundle:code:create" }
    requirements: { _method: post }

admin_codes_edit:
    path:     /{id}/edit
    defaults: { _controller: "EdpMainBundle:code:edit" }

admin_codes_update:
    path:     /{id}/update
    defaults: { _controller: "EdpMainBundle:code:update" }
    requirements: { _method: post|put }

admin_codes_delete:
    path:     /{id}/delete
    defaults: { _controller: "EdpMainBundle:code:delete" }
    requirements: { _method: post|delete }
