<?php

namespace Edp\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * abonnementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class abonnementRepository extends EntityRepository
{
 
    /**
     * Récupérer les abonnements qui utilisent un code en particulier (avec jointure sur entity utilisateur)
     * @param array $codes
     * @return res
     */
    public function getAboByCode(array $codes) {
        $q = $this->createQueryBuilder("a");
            $q->join('a.utilisateurs','u')
              ->where($q->expr()->in('a.id',$codes));   
            return $q->getQuery()->getResult();
    }
}

//OU
//public function getAboByCode(array $codes) {
//        $q = $this->createQueryBuilder("a");
//            $q->join('a.utilisateurs','u')
//              ->join('a.codes','c')
//              ->where($q->expr()->in('c.id',$codes));   
//            return $q->getQuery()->getResult();
//    }