<?php

namespace Edp\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * adresse_utilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class adresse_utilisateurRepository extends EntityRepository
{
}
