<?php

namespace Edp\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * codeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class codeRepository extends EntityRepository
{
}
