<?php

namespace Edp\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * motclefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class motclefRepository extends EntityRepository
{
}
