services:
    acme_user.registration.form.type:
        class: Edp\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: edp_user_registration }